replicaCount: 1

image:
  repository: oamdev/terraform-controller
  tag: 0.2.8
  pullPolicy: Always

gitImage: alpine/git:latest
busyboxImage: busybox:latest
terraformImage: oamdev/docker-terraform:1.0.9

backend:
  namespace: vela-system

githubBlocked: false
